### ISSUE TITLE
Battery status reading

### ISSUE THREAD

**Issue by RussianNeuroMancer** [aarch64-laptops/build#11]
Hello!

Maybe it's good idea to add "Battery status" into list of supported features on https://github.com/aarch64-laptops/build page?

In my case on Lenovo Yoga C630 WOS battery status is not available by default, however updating kernel from 5.0.0 to 5.2.0 (from [PPA](https://launchpad.net/~aarch64-laptops/+archive/ubuntu/all)) and adding acpi=force to grub.cfg allow to workaround this issue.

**Comment by RussianNeuroMancer** [comment]
> adding acpi=force to grub.cfg allow to workaround this issue

...but it's seems like acpi=force break USB devices support, so due to lack of WiFI and LTE this is no go for now.

**Comment by lag-linaro** [comment]
> ...but it's seems like acpi=force break USB devices support, so due to lack of WiFI and LTE this is no go for now.

Only the right port is nonoperational when booting with ACPI.  The left one should work fine.

**Comment by RussianNeuroMancer** [comment]
I see, thank you for this information! I will try to boot device from microSD attached via USB hub.

**Comment by RussianNeuroMancer** [comment]
As I just found booting from storage device attached to laptop via USB hub seems like not supported by firmware. At least if this storage device is microSD card reader.

**Comment by lag-linaro** [comment]
Doesn't work for me when using a USB flash drive either.

**Comment by RussianNeuroMancer** [comment]
Battery status is present with 5.3rc1 kernel.
