### ISSUE TITLE
Linux 5.3rc1 from gpu branch doesn't boot on Lenovo Yoga C630 WOS

### ISSUE THREAD

**Issue by RussianNeuroMancer** [aarch64-laptops/build#13]
Hello!

I find that Linux 5.3rc1 from [gpu branch](https://github.com/aarch64-laptops/linux/tree/gpu) doesn't boot on Lenovo Yoga C630 WOS. Boot stuck at following error message:

EFI stub: Booting Linux Kernel...
EFI stub: Using DTB from configuration table
found a panel-id!
EFI stub: Exiting boot services and installing virtual address map...

How kernel was installed:
[sdm850-lenovo-yoga-c630.dtb](https://github.com/aarch64-laptops/build/blob/master/misc/lenovo-yoga-c630/gpu/dtb/sdm850-lenovo-yoga-c630.dtb) copied to /boot (not sure, if this was necessary, as sdm850-lenovo-yoga-c630.dtb is also present in /usr/lib/linux-image-5.3.0-rc1-00055-g3b90f3cd6c59/qcom/ anyway).
[firmware](https://github.com/aarch64-laptops/build/tree/master/misc/lenovo-yoga-c630/gpu/firmware) copied to /lib/libfirmware/qcom
[linux-image-5.3.0-rc1_arm64-gpu.deb](https://github.com/aarch64-laptops/build/blob/master/misc/lenovo-yoga-c630/gpu/debs/linux-image-5.3.0-rc1_arm64-gpu.deb) was installed with dpkg.
Workaround from issue #10 was removed (file /boot/laptop.dtb is deleted) just in case.

**Comment by lag-linaro** [comment]
What does your grub entry look like?

**Comment by RussianNeuroMancer** [comment]
> What does your grub entry look like?

```
menuentry 'Ubuntu GNU/Linux' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-66e85825-5c21-4120-b4ee-e17e4cdc1e58' {
	load_video
	insmod gzio
	insmod part_gpt
	insmod ext2
	set root='hd1,gpt2'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-ieee1275='ieee1275/(null)/sas/disk@0\,1000000000000,gpt2' --hint-bios=hd1,gpt2 --hint-efi=hd1,gpt2 --hint-baremetal=ahci1,gpt2  66e85825-5c21-4120-b4ee-e17e4cdc1e58
	else
	  search --no-floppy --fs-uuid --set=root 66e85825-5c21-4120-b4ee-e17e4cdc1e58
	fi
	echo	'Загружается Linux 5.3.0-rc1-00055-g3b90f3cd6c59 …'
	linux	/boot/vmlinuz-5.3.0-rc1-00055-g3b90f3cd6c59 root=UUID=66e85825-5c21-4120-b4ee-e17e4cdc1e58 ro   efi=novamap ignore_loglevel clk_ignore_unused pd_ignore_unused console=tty0
	echo	'Загружается начальный виртуальный диск …'
	initrd	/boot/initrd.img-5.3.0-rc1-00055-g3b90f3cd6c59
	echo	'Loading device tree ...'
	devicetree /boot/laptop.dtb
}
```

Just in case I attached full grub.cfg: 
[grub.cfg](https://github.com/aarch64-laptops/build/files/3472330/grub.txt)

By the way, was this step necessary?

> file /boot/laptop.dtb is deleted

Or I should been rename sdm850-lenovo-yoga-c630.dtb to laptop.dtb? Or this is unrelated to 5.3 release at all?

**Comment by lag-linaro** [comment]
> Or I should been rename sdm850-lenovo-yoga-c630.dtb to laptop.dtb?

Yes, that will work.  Or just create a symbolic link.

**Comment by RussianNeuroMancer** [comment]
Tried that to sdm850-lenovo-yoga-c630.dtb to laptop.dtb, still stuck at "EFI stub: Exiting boot services and installing virtual address map..."

Also tried `acpi=force` - this does not help too.

**Comment by lag-linaro** [comment]
Try putting this on the kernel commandline `earlycon=efifb`.

**Comment by RussianNeuroMancer** [comment]
> Try putting this on the kernel commandline earlycon=efifb

Yes, this did help to get to the desktop few times. Most of the times rendering get stuck on "printk: bootconsole [efifb0] disabled" (below quote from dmesg_gpu2)

```
[   50.584726] msm_dsi_manager_register: failed to register mipi dsi host for DSI 0
[   50.584868] msm ae00000.mdss: failed to bind ae94000.dsi (ops dsi_ops [msm]): -517
[   50.584979] msm ae00000.mdss: master bind failed: -517
[   50.591036] msm ae00000.mdss: bound ae01000.mdp (ops dpu_ops [msm])
[   50.591145] msm_dsi ae94000.dsi: ae94000.dsi supply gdsc not found, using dummy regulator
[   50.591323] msm_dsi_manager_register: failed to register mipi dsi host for DSI 0
[   50.591398] msm ae00000.mdss: failed to bind ae94000.dsi (ops dsi_ops [msm]): -517
[   50.591470] msm ae00000.mdss: master bind failed: -517
[   50.595253] msm ae00000.mdss: bound ae01000.mdp (ops dpu_ops [msm])
[   50.595340] msm_dsi ae94000.dsi: ae94000.dsi supply gdsc not found, using dummy regulator
[   50.595503] msm_dsi_manager_register: failed to register mipi dsi host for DSI 0
[   50.595557] msm ae00000.mdss: failed to bind ae94000.dsi (ops dsi_ops [msm]): -517
[   50.595626] msm ae00000.mdss: master bind failed: -517
[   50.599250] msm ae00000.mdss: bound ae01000.mdp (ops dpu_ops [msm])
[   50.599354] msm_dsi ae94000.dsi: ae94000.dsi supply gdsc not found, using dummy regulator
[   50.599534] msm_dsi_host_set_src_pll: can't set parent to byte_clk_src. ret=-22
[   50.599542] msm_dsi_manager_register: failed to register mipi dsi host for DSI 0
[   50.599615] msm ae00000.mdss: failed to bind ae94000.dsi (ops dsi_ops [msm]): -22
[   50.599689] msm ae00000.mdss: master bind failed: -22
[   50.600701] msm: probe of ae00000.mdss failed with error -22
```

Sometimes I managed to get to the desktop. Unfortunately, there is still some issue with rendering: 
https://ibb.co/XV4dVBF
https://ibb.co/Mg71bxt
And as you can see in gmesg_gpu1, 3, 4 there is also adreno error messages:

```
[   50.462842] msm ae00000.mdss: Adding to iommu group 4
[   50.466145] msm ae00000.mdss: bound ae01000.mdp (ops dpu_ops [msm])
[   50.466237] msm_dsi ae94000.dsi: ae94000.dsi supply gdsc not found, using dummy regulator
[   50.466554] msm ae00000.mdss: bound ae94000.dsi (ops dsi_ops [msm])
[   50.466856] adreno 5000000.gpu: 5000000.gpu supply vdd not found, using dummy regulator
[   50.466908] adreno 5000000.gpu: 5000000.gpu supply vddcx not found, using dummy regulator
[   50.467069] msm ae00000.mdss: [drm:msm_gpu_init [msm]] A630: using IOMMU
[   50.467429] platform 506a000.gmu: Adding to iommu group 5
[   50.467997] msm ae00000.mdss: bound 5000000.gpu (ops a3xx_ops [msm])
[   50.468116] msm_dpu ae01000.mdp: [drm:msm_ioremap [msm]] *ERROR* failed to get memory resource: vbif_nrt
[   50.468165] msm_dpu ae01000.mdp: [drm:msm_ioremap [msm]] *ERROR* failed to get memory resource: regdma
[   50.468195] [drm:dpu_kms_hw_init:842] dpu hardware revision:0x40000000
...
[   50.511414] msm ae00000.mdss: [drm:adreno_request_fw [msm]] loaded qcom/a630_sqe.fw from new location
[   50.512768] msm ae00000.mdss: [drm:adreno_request_fw [msm]] loaded qcom/a630_gmu.bin from new location
[   50.526177] msm ae00000.mdss: [drm:adreno_request_fw [msm]] loaded qcom/a630_zap.mdt from new location
...
[   52.572401] [drm:_dpu_crtc_wait_for_frame_done [msm]] *ERROR* frame done wait timed out, ret:0
[   52.573454] [drm:dpu_crtc_commit_kickoff:660] [dpu error]crtc57 wait for frame done failed;frame_pending0
[   52.792391] [drm:_dpu_crtc_wait_for_frame_done [msm]] *ERROR* frame done wait timed out, ret:0
[   52.792395] [drm:dpu_crtc_commit_kickoff:660] [dpu error]crtc57 wait for frame done failed;frame_pending0
[   52.888393] [drm:_dpu_crtc_wait_for_frame_done [msm]] *ERROR* frame done wait timed out, ret:0
[   52.889847] [drm:dpu_crtc_commit_kickoff:660] [dpu error]crtc57 wait for frame done failed;frame_pending1
...

[   73.418197] adreno 5000000.gpu: [drm:a6xx_irq [msm]] *ERROR* gpu fault ring 0 fence 434 status 00800005 rb 0292/0292 ib1 00000000057AA000/011a ib2 0000000004472500/0000
[   73.419065] msm ae00000.mdss: [drm:recover_worker [msm]] *ERROR* A630: hangcheck recover!
[   73.419111] msm ae00000.mdss: [drm:recover_worker [msm]] *ERROR* A630: offending task: g:flush_queue0 (/usr/bin/gnome-shell)
[   73.491583] revision: 630 (6.3.0.2)
[   73.491588] rb 0: fence:    1075/1076
[   73.491591] rptr:     640
[   73.491593] rb wptr:  658
[   73.491637] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG0: 0
[   73.491672] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG1: 0
[   73.491706] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG2: 1075
[   73.491740] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG3: 0
[   73.491774] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG4: 0
[   73.491808] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG5: 1086
[   73.491842] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG6: 1110
[   73.491875] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG7: 1109
```

Logs: 
[dmesg_gpu.zip](https://github.com/aarch64-laptops/build/files/3472876/dmesg_gpu.zip)

**Comment by lag-linaro** [comment]
Did you install the kernel before or after putting the F/W into /lib/firmware?

Can you try rebuilding the initramfs?

**Comment by RussianNeuroMancer** [comment]
> Did you install the kernel before or after putting the F/W into /lib/firmware?

After.

> Can you try rebuilding the initramfs?

Tried to run "sudo update-initramfs -u", power cycle, issue described in my previous comment is still reproducible.

**Comment by robclark** [comment]
> ```
> [   73.418197] adreno 5000000.gpu: [drm:a6xx_irq [msm]] *ERROR* gpu fault ring 0 fence 434 status 00800005 rb 0292/0292 ib1 00000000057AA000/011a ib2 0000000004472500/0000
> [   73.419065] msm ae00000.mdss: [drm:recover_worker [msm]] *ERROR* A630: hangcheck recover!
> [   73.419111] msm ae00000.mdss: [drm:recover_worker [msm]] *ERROR* A630: offending task: g:flush_queue0 (/usr/bin/gnome-shell)
> [   73.491583] revision: 630 (6.3.0.2)
> [   73.491588] rb 0: fence:    1075/1076
> [   73.491591] rptr:     640
> [   73.491593] rb wptr:  658
> [   73.491637] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG0: 0
> [   73.491672] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG1: 0
> [   73.491706] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG2: 1075
> [   73.491740] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG3: 0
> [   73.491774] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG4: 0
> [   73.491808] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG5: 1086
> [   73.491842] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG6: 1110
> [   73.491875] adreno 5000000.gpu: [drm:a6xx_recover [msm]] CP_SCRATCH_REG7: 1109
> ```

It wasn't clear if you are still seeing this, but you need mesa newer than 19.1 (or to find an older a630_sqe.fw from, for example, pixel3)..

**Comment by RussianNeuroMancer** [comment]
@robclark 

> you need mesa newer than 19.1

yes, this is exactly what missing - after Ubuntu upgrade from 19.04 to to 19.10 ([Mesa 19.0.2 to 19.1.2](https://launchpad.net/ubuntu/+source/mesa)) hardware acceleration is working.

> It wasn't clear if you are still seeing this

This error doesn't appear anymore. "frame done wait timed out" error is still here, but I guess it's expected at this point, so I shouldn't register separate issue about it?

**Comment by robclark** [comment]
> @robclark
> 
> > you need mesa newer than 19.1
> 
> yes, this is exactly what missing - after Ubuntu upgrade from 19.04 to to 19.10 ([Mesa 19.0.2 to 19.1.2](https://launchpad.net/ubuntu/+source/mesa)) hardware acceleration is working.
> 
> > It wasn't clear if you are still seeing this
> 
> This error doesn't appear anymore. "frame done wait timed out" error is still here, but I guess it's expected at this point, so I shouldn't register separate issue about it?

the "frame done" timeout is "expected".. I've not had a chance to investigate what is going on there, but seems to be harmless (other than annoying)

**Comment by lag-linaro** [comment]
Thanks @robclark

**Comment by RussianNeuroMancer** [comment]
@robclark 

Indeed, thank you for helping me out :)
