### ISSUE TITLE
Ubuntu update hangs

### ISSUE THREAD

**Issue by rhenwood-arm** [aarch64-laptops/build#19]
Looks like there is some problem with 'snapd'. It causes the 'apt upgrade' command to hang on my system.

The 'work-around' is to open another window, and 'pkill snapd' which unblocks the update. While this allows the upgrade to complete, I feel like there may be a better solution.

**Comment by RussianNeuroMancer** [comment]
Another workaround that works for me is purging snapd before upgrade.

**Comment by dtischler** [comment]
Just used Richard's workaround to resolve my hung "apt-get upgrade"...worked great!

**Comment by lag-linaro** [comment]
This doesn't sound like an AArch64 Laptops issue.

Have you reported this to Ubuntu (Canonical) via Launchpad?

**Comment by lag-linaro** [comment]
Instructions on upgrading, including how to fix this issue, now available:

https://github.com/aarch64-laptops/build#updating-from-an-older-imageinstaller
