### ISSUE TITLE
Kernel doesn't boot after update

### ISSUE THREAD

**Issue by rhenwood-arm** [aarch64-laptops/build#20]
The kernel command line needs 'efi=novamap'. This may get dropped after 'update-grub2' is run -- which may happen after automatic kernel upgrade.

For a permanent solution, you can add 'efi=novamap' into the GRUB_CMDLINE_LINUX_DEFAULT string in this file:

/etc/default/grub

**Comment by lag-linaro** [comment]
Instructions on upgrading, including how to fix this issue, now available:

https://github.com/aarch64-laptops/build#updating-from-an-older-imageinstaller
