### ISSUE TITLE
Sound unsupported

### ISSUE THREAD

**Issue by NiQ1** [aarch64-laptops/build#21]
The Qualcomm Aqstic sound device does not seem to be supported, which means no sound whatsoever (at least not on my Yoga C630).
If someone else has sound working I'd like to know that. If it's indeed unsupported at this point please add it to the list of unsupported features on the main page so people know not to expect that.

Thanks.

**Comment by lag-linaro** [comment]
Thanks for the report.

Fixed by: https://github.com/aarch64-laptops/build/commit/50f934005cb95104ed659dba030c6a20629311de
