### ISSUE TITLE
Status of wifi for ASUS NovaGo TP370QL?

### ISSUE THREAD

**Issue by monperrus** [aarch64-laptops/build#22]
Hi and thanks for the great repo.

What are the bug reports related to broken wifi for ASUS NovaGo TP370QL?

**Comment by lag-linaro** [comment]
Not sure anyone has looked into WiFi on the TP370QL.

However, if it's anything like the Lenovo Yoga C630 it will be tough to get going.

See #24 for more details.

**Comment by monperrus** [comment]
OK, thanks a lot for your answer.

What's the kernel module which has to be improved for supporting Wifi?

**Comment by lag-linaro** [comment]
If only it was as easy as that.

Unfortunately, there are lots of firmware and userspace applications involved too.

I plan on drafting a HOWTO to get to our current state (which is not a stable one).

**Comment by monperrus** [comment]
> I plan on drafting a HOWTO to get to our current state (which is not a stable one).

Looking forward to it :-)

**Comment by lag-linaro** [comment]
Not sure how relevant this will be for the TP370QL, but it has to be worth a shot:

https://github.com/aarch64-laptops/build/tree/master/misc/lenovo-yoga-c630/wifi
