### ISSUE TITLE
403 (Forbidden) trying to download the GPU prebuilt image

### ISSUE THREAD

**Issue by klardotsh** [aarch64-laptops/build#26]
I see in the directory listing that http://people.linaro.org/~lee.jones/aarch64laptops/aarch64-laptops-eoan-gpu.img.xz exists, but

```
You don't have permission to access /~lee.jones/aarch64laptops/aarch64-laptops-eoan-gpu.img.xz on this server.
```

**Comment by lag-linaro** [comment]
Apologies, please try again.

**Comment by klardotsh** [comment]
Was able to download and flash no problem (and SuperTuxKart plays! though USB docked ethernet doesn't appear to work - that's another issue entirely)

Cheers!
