### ISSUE TITLE
No mention of other distros

### ISSUE THREAD

**Issue by bkeys-RFA** [aarch64-laptops/build#4]
Is there a documented way to experiment with other linux distros on aarch64 laptops? I would be interested in seeing if a Fedora port is possible

**Comment by lag-linaro** [comment]
Doing so is not documented, but it shouldn't be too difficult given some basic distro understanding.

Doing so either requires knowledge of how to interact with the installer/live-disk filesystem (kernel, initramfs, device trees, etc) or the ability to look-up/acquire said knowledge.

For ad-hoc guidance and/or hints to get over small obstacles, you can try our IRC channel:

`aarch64-laptops` on `freenode`.
