### ISSUE TITLE
nice project!

### ISSUE THREAD

**Issue by Askmewho** [aarch64-laptops/build#55]
Hi! I wonder why you cant get hw acceleration having freedreno... you cant use a proper kernel to get access to the gpu?? 

also, check this out, I am testing an x86 emulator with hw acceleration https://www.youtube.com/watch?v=KIWePlAbLUs
I have tons of videos but this one was on aarch64 with multiarch (box86 is armhf only)

https://github.com/ptitSeb/box86

**Comment by lag-linaro** [comment]
One for you I think @robclark.

**Comment by robclark** [comment]
umm, is it?  I've been using freedreno on my c630 for.. well I guess at least more than a year now.

(It requires devicetree boot, but basically everything needed for these laptops to be usable does)

**Comment by Askmewho** [comment]
You mean a proper dtb.. I didn't know you can even boot without it

**Comment by lag-linaro** [comment]
> You mean a proper dtb.. I didn't know you can even boot without it.

Yes you can.  It also boots with ACPI.

The laptops are not designed for makers.

If you want a maker version, please see the 96Boards project and the like.
