### ISSUE TITLE
Update the kernel source

### ISSUE THREAD

**Issue by jallum** [aarch64-laptops/build#6]
It appears that the ./quick-start.sh scripts will install a version of the kernel from the PPA (5.0.1) that's newer than the source linked in the linux submodule (5.0-rc5).  If rebuilding from source, which branch should we be using to reproduce what's in the PPA?

**Comment by lag-linaro** [comment]
Actually the kernel in the PPA is not newer, despite the slightly misleading versioning.

The one in the PPA is 5.0-rc5 as well.

Out of interest, what are you trying to do?

**Comment by jallum** [comment]
Understood.  I see what's happening with the versioning now -- it _is_ a little confusing.  I'm trying to get my bearings on the project and saw the version mismatch, and (wrongly) assumed that it meant that I would be looking at out of date source.  Since I couldn't find an official release tagged 5.0.1, I was hoping the maintainer would bring the source up to date.
