### ISSUE TITLE
Add support for Allview Allbook Q

### ISSUE THREAD

**Issue by paulstelian97** [aarch64-laptops/build#61]
Hello, I've just got a new Allview Allbook Q, which comes with Windows 10 Home. It doesn't seem to be among your supported laptops so I want to help out.

But first, what do I need to do to help? What should I provide, what should I test on my own etc.

SoC: Snapdragon 835
Internal storage: UFS (Universal Flash Storage) from Qualcomm. I assume already supported.
iGPU: Adreno 540
Touchpad + keyboard: I2C HID device (ACPI\QCOM001F\6 for bus, ACPI\QTEC0001\3 for device)

Any other details, available on request (as long as you can tell me how to get them). I can run acpidump on this system as well (32-bit x86 executables work since it's regular Windows 10).

**Comment by rhenwood-arm** [comment]
Welcome @paulstelian97 !

I suggest the first thing to do is follow the instructions for https://github.com/aarch64-laptops/build#booting-into-Ubuntu to disable secure boot and try booting the special Ubuntu 18.04 installer: https://pskov.surgut.co.uk/bionic/daily-live/current/ The install should boot up off a USB drive. NOTE: Some folks have observed sensitivities to drive size, physical port, and Windows firmware versions, you may need to try variations of drive, port etc.

If the installer comes up - that is good news. After that you can decide if you want to follow the instructions to create a dual-boot environment.

Please let us know how you get on :)

**Comment by paulstelian97** [comment]
Dual boot won't be possible because internal eMMC is 64GB. Otherwise I'll try as soon as I can.

**Comment by paulstelian97** [comment]
HP devicetree: I can boot and can use USB mouse. Builtin touchpad (I2C according to Windows' Device Manager) doesn't work. Also very slow and dmesg is full of errors. lspci is empty (no PCI buses). Wi-Fi card not detected. Battery not detected. Builtin sound not detected. xrandr "Failed to get size of gamma for output default" and claims 77Hz (which I think is false). USB works, of course.

lscpu reports:

```
Architecture: aarch64
Byte Order: Little Endian
CPU(s): 8
On-line CPU(s) list: 0-7
Threads(s) per core: 1
Core(s) per socket: 4
Socket(s): 2
NUMA node(s): 1
Vendor ID: Qualcomm
Model: 4
Model name: Kryo V2
Stepping: 0xa
BogoMIPS: 38.40
L1d cache: unknown size
L1i cache: unknown size
L2 cache: unknown size
NUMA node0 CPU(s): 0-7
Flags: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
```

I notice that the keyboard is supported because of an OF node (firmware/devicetree/base/soc/i2c@c17a000/keyboard@3a). Guess that one just lucked out or is there some standardization there?

Anyway, long way to go until everything works fine. But this looks like a starting point?

**Comment by paulstelian97** [comment]
[ACPI.zip](https://github.com/aarch64-laptops/build/files/5394733/ACPI.zip)
ACPI tables, extracted from one of those weird disks (apparently the dd dumps might be corrupted or something)

[QCOM.zip](https://github.com/aarch64-laptops/build/files/5394738/QCOM.zip)
Some .PROVISION files. Not sure what they are used for but I think they may be necessary inside the DT? Removed MSDM.ACP (which I think contains my Windows 10 Home OEM serial key).

[TZAPPS.zip](https://github.com/aarch64-laptops/build/files/5394739/TZAPPS.zip)
No clue what this is but I found it so yeah.

**Comment by paulstelian97** [comment]
I no longer own the device, so I'm closing this. If someone else has this device, feel free to reopen the issue.
