### ISSUE TITLE
Huawei Matebook E 2019 Support

### ISSUE THREAD

**Issue by JoveYu** [aarch64-laptops/build#73]
anyone know how to install any Linux distribution on Huawei Matebook E 2019 with Snapdragon 850?

**Comment by coolduke666** [comment]
have you received any feedback? have also a matebook E 2019 and my win10 doesn't boot anymore. System recovery doesn't work either... so I will try to install linux...

**Comment by riverzhou** [comment]
have you received any feedback? I wanna install linux to my Huawei Matebook E 2019 too.

**Comment by coolduke666** [comment]
I got no feedback..

RiverZhou ***@***.***> schrieb am Di., 22. Feb. 2022, 16:47:

**Comment by riverzhou** [comment]
![IMG_20220226_235400](https://user-images.githubusercontent.com/1277270/155850544-83d90dc8-7a8c-4f25-a4dc-765ef646c07a.jpg)
![IMG_20220226_235412](https://user-images.githubusercontent.com/1277270/155850548-06371d28-e7a0-4cbe-b569-20a6fd3de300.jpg)
![IMG_20220226_235445](https://user-images.githubusercontent.com/1277270/155850549-13ceff74-88b2-4fa2-9259-90a3b5001caf.jpg)

**Comment by coolduke666** [comment]
Nice. Which distribution? Which linux image?


RiverZhou ***@***.***> schrieb am Sa., 26. Feb. 2022, 17:20:

**Comment by riverzhou** [comment]
It's not a distribution, it's just kernel+busybox.
I build grub + kernel + busybox from source and boot it on Matebook E 2019.
My kernel source code is at https://github.com/riverzhou/matebooke2019kernel.git .

> Nice. Which distribution? Which linux image? RiverZhou ***@***.***> schrieb am Sa., 26. Feb. 2022, 17:20:
> […](#)
> anyone know how to install any Linux distribution on Huawei Matebook E 2019 with Snapdragon 850? Succeed booting 5.15.25 kernel to busybox on Matebook E 2019. — Reply to this email directly, view it on GitHub <[#73 (comment)]

**Comment by kmille36** [comment]
Any new? I want too.

**Comment by riverzhou** [comment]
https://github.com/riverzhou/matebooke2019kernel.git

**Comment by WalleoAndrew** [comment]
> https://github.com/riverzhou/matebooke2019kernel.git
> 
> 我将内核更新到 6.3.2

有可提供的固件吗，我没有任何固件

**Comment by kmille36** [comment]
> https://github.com/riverzhou/matebooke2019kernel.git
> 
> I updated kernel to 6.3.2

Can i have a flash image file. Thanks.
