### ISSUE TITLE
Snapdragon 8cx Gen 1-2-3 support

### ISSUE THREAD

**Issue by alfredonodo** [aarch64-laptops/build#91]
Hi,
do you have any update for snapdragon 8cx support?
-   Gen 3 SC8280 is fully supported by [linux kernel 5.19](https://www.linaro.org/blog/linaro-featured-top-in-5-19-linux-kernel-release-the-first-kernel-to-be-released-on-arm64/).
-   Gen 1 SC8180X should be supported starting from [linux kernel 6.1](https://git.linaro.org/landing-teams/working/qualcomm/kernel.git/commit/?id=40285e64c5654c956505dad34ed2ee4be163b1f0).
-   Gen 2 SC8180XP [unknown](https://git.linaro.org/landing-teams/working/qualcomm/kernel.git/log/?qt=grep&q=SC8180XP).

I have a lenovo ideaPad 5G 14Q8X05 with snapdragon 8cx gen 2.

Thank you

**Comment by aminasyan** [comment]
I have a DELL Inspiron 14 3420 with Qualcomm Snapdragon 8cx Gen 2 (sc8180xp)
I'm attaching acpidump files.
[acpidump.zip](https://github.com/aarch64-laptops/build/files/14639968/acpidump.zip)

**Comment by alfredonodo** [comment]
Hi,
there are some updates. Currently the linux kernel supports almost all snapdragon 8cx SoCs:

- [gen 1 SC8180X Lenovo Flex 5G](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.5)
- [gen 3 SC8280XP Lenovo Thinkpad X13s](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.0)
- [gen 4 /X Elite X1E80100](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.8)

SoC SC8180XP which is the evolution of the Flex one with the same CPU-GPU, but at higher frequency, with BT 5.1 and WiFi 6 instead of BT 5 and WiFi 5·
Other members of the community are also [asking the same thing](https://bugzilla.kernel.org/show_bug.cgi?id=218512) and wondering why it is so. Perhaps you can post the debug there.

**Comment by alfredonodo** [comment]
This is my dump for Lenovo IdeaPad 5G 14Q8X05
[ACPI.zip](https://github.com/aarch64-laptops/build/files/14700163/ACPI.zip)

**Comment by alfredonodo** [comment]
[Qualcomm has announced Upstreaming Linux kernel support for the Snapdragon X Elite](https://www.qualcomm.com/developer/blog/2024/05/upstreaming-linux-kernel-support-for-the-snapdragon-x-elite).

_Collaborating with Lenovo, Arm and Linaro on the AArch64 laptops GitHub project, we’ve built Linux support into several generations of our SoCs with Windows on Snapdragon. We’ve ensured that you could boot Linux on many of the laptops powered by our previous generation of SoCs. Notable models include the Lenovo Yoga C630 (Snapdragon 850), the Lenovo Flex 5G (Snapdragon 8cx Gen 1) and the Lenovo ThinkPad X13s (Snapdragon 8cx Gen 3)._

In the description, all SoC 8cx are included except the unfortunate Gen 2 (sc8180xp). Who knows why it is the only one excluded.

**Comment by sirredbeard** [comment]
Dupe of #76

**Comment by alfredonodo** [comment]
> ACPI.zip

Thank you
